# Site settings
title: Tales of Murder
email: TalesofMurderPress@gmail.com
description: "For readers with time to kill!"
baseurl: ""
url: "http://talesofmurder.com"
twitter_username: talesofmurder
github_username:  flaturtha

# Build settings
markdown: kramdown
permalink: pretty
